accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path


from accounts.views import signup

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name='logout'),
    path("signup/", signup, name='signup')
  
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('receipts/', include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.urls import path
from receipts.views import (
    ReceiptListView, ReceiptAccountsCreateView, ExpenseCategoryCreateView, ReceiptCreateView, ExpenseCategoryListView, AccountListView
 
)

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path(
        "accounts/create/",
        ReceiptAccountsCreateView.as_view(),
        name="accounts_create",
    ),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="categories_create",
    ),
    path("create/", ReceiptCreateView.as_view(), name="receipt_create"),
    path("categories/", ExpenseCategoryListView.as_view(), name="receipt_category_list"),
    path("accounts/", AccountListView.as_view(), name="receipt_account_list")
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings
USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField( max_length = 50)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
        null=True
    )
    def __str__(self):
        return self.name

class Account(models.Model):
    name = models.CharField(max_length = 100)
    number = models.CharField(max_length = 20)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
        null=True
    )

    def __str__(self):
        return self.name

class Receipt(models.Model):
    vendor = models.CharField(max_length = 200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField(auto_now_add = True)
    purchaser = models.ForeignKey(
        USER_MODEL,
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        ExpenseCategory,
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    account = models.ForeignKey(
        Account,
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True
    )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login

# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid:
            username = request.POST["username"] 
            password = request.POST["password1"]
            user = User.objects.create_user(username, password=password)
            user.save()
            login(request, user)
            return redirect("home") 
    else:
        form = UserCreationForm(request.POST)
    context = {"form":form}
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from receipts.models import Receipt, Account, ExpenseCategory

# Create your views here.
class ReceiptListView(LoginRequiredMixin, ListView):
    template_name = "receipts/list.html"
    model = Receipt
    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)

 
class ReceiptAccountsCreateView(LoginRequiredMixin, CreateView):
    template_name = "receipts/accounts_create.html"
    model = Account
    fields = ["name", "number"]
    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("receipt_account_list")


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    template_name = "receipts/categories_create.html"
    model = ExpenseCategory
    fields = ["name"]
    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("receipt_category_list")



class ReceiptCreateView(LoginRequiredMixin, CreateView):
    template_name = "receipts/create.html"
    model = Receipt
    fields = ["vendor", "total", "tax", "date", "category", "account"]
    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")

class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    template_name = "receipts/categories_list.html"
    model = ExpenseCategory
    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)

class AccountListView(LoginRequiredMixin, ListView):
    template_name = "receipts/accounts_list.html"
    model = Account
    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)

  

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Receipts</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'receipt_create' %}">Create Receipt Account</a>
                </li>
                <li>
                    <a href="{% url 'categories_create' %}">Create Expense Category</a>
                </li>
                <li>
                    <a href="{% url 'logout' %}">Logout</a>
                </li>

                {% else %}
                <li>
                    <a href="{% url 'signup' %}">Sign Up</a>
                </li>
                <li>
                    <a href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    {% block content %}
    {% endblock content %}
</body>
</html>

receipts/templates/receipts/accounts_create.html
{% extends 'base.html' %}
{% block content %}
<h2>Create Account</h2>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Create Account</button>
</form>
{% endblock content %}

receipts/templates/receipts/accounts_list.html
{% extends 'base.html' %}
{% block content %}
<h1>Account</h1>

{% endblock content %}

receipts/templates/receipts/categories_create.html
{% extends 'base.html' %}
{% block content %}
<h2>Create Expense</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create Expense</button>
</form>
{% endblock content %}

receipts/templates/receipts/categories_list.html
{% extends 'base.html' %}
{% block content %}
<h1>Expenses List</h1>

{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %}
{% block content %}
<h2>Create Receipt</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create Receipt</button>
</form>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}
{% block content %}
<h1>Home</h1>
<table>
    <thead> 
        <tr>
            <th> Vendor </th>
            <th> Total </th>
            <th> Tax </th>
            <th> Date </th>
            <th> Category </th>
            <th> Accounts </th>
        </tr>
    </thead>
    <tbody>
    {% comment %} {% for receipt in receipt_list %} {% endcomment %}
        <tr>
            <td> receipt.vendor </td>
            <td> receipt.total </td>
            <td> receipt.tax </td>
            <td> receipt.date </td>
            <td> receipt.category </td>
            <td> receipt.account </td>
        </tr>
    {% comment %} {% endfor %} {% endcomment %}
    </tbody>
</table>
{% endblock content %}